version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.8.2-rc-focal
    volumes:
      - mrdata:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MARIADB_USER=${DB_USERNAME}"
      - "MARIADB_PASSWORD=${DB_PASSWORD}"
      - "MARIADB_DATABASE=${DB_DATABASE}"
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    image: phpmyadmin:5.1.3
    links:
      - "mariadb:db"
    container_name: phpmyadmin
    ports:
      - 60080:80
volumes:
  mrdata:
